# Generated by Django 6.0.2 on 2026-02-16 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('community', 'Community'), ('mentors_only', 'Mentors only'), ('private', 'Private')], default='community', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.document')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.tag')),
            ],
            options={
                'unique_together': {('document', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='documents', through='docs.DocumentTag', to='docs.tag'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('body_md', models.TextField()),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_document_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='docs.document')),
            ],
            options={
                'indexes': [models.Index(fields=['document', 'version_number'], name='docs_docume_documen_bccab2_idx')],
                'unique_together': {('document', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['visibility', 'created_at'], name='docs_docume_visibil_59d59f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['project', 'created_at'], name='docs_docume_project_354297_idx'),
        ),
    ]
